-- 코드를 입력하세요
SELECT m.MEMBER_NAME, r1.REVIEW_TEXT, DATE_FORMAT(r1.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE m
JOIN REST_REVIEW r1 ON m.MEMBER_ID = r1.MEMBER_ID
WHERE r1.MEMBER_ID = (
    SELECT r2.MEMBER_ID FROM REST_REVIEW r2
    WHERE r2.MEMBER_ID IS NOT NULL
    GROUP BY r2.MEMBER_ID
    ORDER BY COUNT(r2.REVIEW_ID) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE, r1.REVIEW_TEXT;
