-- 코드를 입력하세요
SELECT MONTH(c1.START_DATE) AS MONTH, c1.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c1
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) IN (8, 9, 10)
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) c2 ON c1.CAR_ID = c2.CAR_ID
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) IN (8, 9, 10)
GROUP BY MONTH, c1.CAR_ID
ORDER BY MONTH, c1.CAR_ID DESC;
